global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3001']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']
