# gameplay-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: MYSQL_TYPE
              value: {{ .Values.database.type }}
            - name: MYSQL_HOST
              value: {{ .Values.database.host }}
            - name: MYSQL_PORT
              value: {{ .Values.database.port | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.database }}
