# gameplay-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: MYSQL_TYPE
              value: {{ .Values.database.type }}
            - name: MYSQL_HOST
              value: {{ .Values.database.host }}
            - name: MYSQL_PORT
              value: {{ .Values.database.port | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.database }}
            - name: SERVICE_SCORE
              value: {{ .Values.url.score }}
            - name: CORS_ORIGIN
              value: {{ .Values.url.cors }}
            - name: SERVICE_BACKGROUND
              value: {{ .Values.url.background }}
            - name: NEXT_PUBLIC_PUB_KEY
              value: {{ .Values.token.pubkey }}
            - name: NEXT_PUBLIC_PRIV_KEY_FAKE
              value: {{ .Values.token.fakePrivKey }}
            - name: NEXT_PUBLIC_PUB_KEY_FAKE
              value: {{ .Values.token.fakePubKey }}
