{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: gameplay-db*/}}
{{/*  namespace: gameplay-api*/}}
{{/*  labels:*/}}
{{/*    app: gameplay-db*/}}
{{/*spec:*/}}
{{/*  replicas: 1*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: gameplay-db*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: gameplay-db*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*        - name: mariadb*/}}
{{/*          image: bitnami/mariadb*/}}
{{/*          envFrom:*/}}
{{/*            - configMapRef:*/}}
{{/*                name: gameplay-env-config*/}}
{{/*          ports:*/}}
{{/*            - containerPort: 3306*/}}
