replicaCount: 1

image:
  repository: anthlr/scalabilite-gameplay-back
  pullPolicy: IfNotPresent

  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:

  create: true

  annotations: {}

  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

auth:
  username: gameplay
  password: gameplay
  database: gameplay
  rootPassword: gameplay

mariadb:
  auth:
    username: "gameplay"
    password: "gameplay"
    database: "gameplay"
    rootPassword: "gameplay"
    host: "mariadb"
  enabled: true
  configMap:
    name: mariadb-config
