# gameplay-api/service.yaml
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# values.yaml

backend:
  image:
    repository: anthlr/scalabilite-gameplay-back
    tag: latest
  port: 3001

database:
  type: mariadb
  host: gameplay-db-mariadb-service
  port: 3306
  username: gameplay
  password: gameplay
  database: gameplay

url:
  score: http://leaddev.digitalseeder.com/wall-of-fame-api
  cors: leaddev.digitalseeder.com
  background: http://leaddev.digitalseeder.com/background-api
